variable "nic_name" { }
variable "nic_location" { }
variable "rg_name" { }
variable "vm_name" { }
variable "vm_location" { }
variable "vm_publisher" { }
variable "vm_offer" { }
variable "vm_sku" { }
variable "vm_osversion" { }
variable "subnet_name" { }